version: '3'

services:
  apache:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-php
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysql
    image: mysql:5.7
    restart: always
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dddlaravel

  vue-ui:
    build:
        context: './frontend'
    ports:
        - "8080:8080"
    container_name: vue-auth
    volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
